
import { Industry, Quality, GenerationFormat, BackgroundStyle, Font, ColorOption, BrandModel, FilterOption } from './types';

export const TRANSLATIONS = {
    en: {
        // App
        projects: "Projects",
        untitledProject: "Untitled Project",
        credits: "Credits",
        sourceMaterial: "Source Material",
        removeBackground: "Remove Background",
        removingBg: "Removing background...",
        removalFailed: "Removal Failed",
        retry: "Retry",
        clickOrDrop: "Click or Drop",
        imageTypes: "JPG, PNG up to 10MB",
        contextDescription: "Context Description",
        contextPlaceholder: "Describe your product and the scene you want to generate...",
        configuration: "Configuration",
        tuneParameters: "Tune parameters for generation.",
        quality: "Quality",
        dimensions: "Dimensions",
        stylePreset: "Style Preset",
        viewAll: "View All",
        showLess: "Show Less",
        unifiedActive: "Unified Background Active",
        generateImage: "Generate Image",
        generating: "Generating...",
        costTime: "Cost: 10 Credits • Est. time 8s",
        zoom: "Zoom",
        compare: "Compare",
        download: "Download",
        yourMasterpiece: "Your masterpiece awaits",
        enterText: "Enter text...",
        generatingLabel: "GENERATING",
        analyzing: "Analyzing source material...",
        composing: "Composing studio scene...",
        infusing: "Infusing cinematic lighting...",
        polishing: "Polishing final details...",
        generationError: "Generation Error",
        settings: "Settings",
        account: "Account",
        studio: "Studio",
        home: "Home",
        changeImage: "Change Image",
        autoMasking: "AI Auto-masking",

        // Auth
        login: "Login",
        signUp: "Sign Up",
        emailAddress: "Email Address",
        emailPlaceholder: "name@example.com",
        password: "Password",
        passwordPlaceholder: "Enter your password",
        createPassword: "Create Password",
        forgotPassword: "Forgot Password?",
        signIn: "Sign In",
        or: "OR",
        continueWithGoogle: "Continue with Google",
        connecting: "Connecting...",
        protectedBy: "Protected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.",
        rightsReserved: "All rights reserved.",
        resetPassword: "Reset your password",
        resetDesc: "Enter the email address associated with your account and we'll send you a link to reset your password.",
        sendResetLink: "Send Reset Link",
        sending: "Sending...",
        backToLogin: "Back to Login",
        checkEmail: "Check your email",
        checkEmailDesc: "We have sent password recovery instructions to your email",
        didntReceive: "Didn't receive the email?",
        clickToResend: "Click to resend",
        createAccount: "Create Account",
        step1: "Step 1 of 3",
        step1Desc: "Start creating pro visuals today.",
        fullName: "Full Name",
        namePlaceholder: "ex. Alex Sterling",
        workEmail: "Work Email",
        workEmailPlaceholder: "name@company.com",
        fair: "Fair",
        weak: "Weak",
        good: "Good",
        strong: "Strong",
        passwordHint: "Use 8+ characters with a mix of letters, numbers & symbols.",
        nextStep: "Next Step",
        alreadyHaveAccount: "Already have an account?",
        customizeStudio: "Customize your Studio",
        almostDone: "ALMOST DONE",
        step2Desc: "Help us tailor the generation models to your specific product niche.",
        primaryIndustry: "Primary Industry",
        estGenerations: "Estimated Monthly Generations",
        completeRegistration: "Complete Registration",
        secureConnection: "Secure & Encrypted Connection",
        goBackStep1: "Go back to step 1",
        needHelp: "Need help? Contact Support"
    },
    vi: {
        // App
        projects: "Dự án",
        untitledProject: "Dự án chưa đặt tên",
        credits: "Tín chỉ",
        sourceMaterial: "Tài nguyên gốc",
        removeBackground: "Xóa nền",
        removingBg: "Đang xóa nền...",
        removalFailed: "Xóa nền thất bại",
        retry: "Thử lại",
        clickOrDrop: "Nhấn hoặc thả ảnh",
        imageTypes: "JPG, PNG tối đa 10MB",
        contextDescription: "Mô tả ngữ cảnh",
        contextPlaceholder: "Mô tả sản phẩm và bối cảnh bạn muốn tạo. Ví dụ: 'Chai nước hoa trên đá rêu trong rừng sương mù...'",
        configuration: "Cấu hình",
        tuneParameters: "Điều chỉnh tham số tạo ảnh.",
        quality: "Chất lượng",
        dimensions: "Kích thước",
        stylePreset: "Phong cách",
        viewAll: "Xem tất cả",
        showLess: "Thu gọn",
        unifiedActive: "Đang dùng nền đồng bộ",
        generateImage: "Tạo hình ảnh",
        generating: "Đang tạo...",
        costTime: "Phí: 10 Tín chỉ • Thời gian ~8s",
        zoom: "Thu phóng",
        compare: "So sánh",
        download: "Tải xuống",
        yourMasterpiece: "Kiệt tác của bạn đang chờ",
        enterText: "Nhập văn bản...",
        generatingLabel: "ĐANG TẠO",
        analyzing: "Đang phân tích tài nguyên...",
        composing: "Đang dựng bối cảnh studio...",
        infusing: "Đang phối ánh sáng điện ảnh...",
        polishing: "Đang hoàn thiện chi tiết...",
        generationError: "Lỗi tạo ảnh",
        settings: "Cài đặt",
        account: "Tài khoản",
        studio: "Studio",
        home: "Trang chủ",
        changeImage: "Đổi ảnh",
        autoMasking: "AI Tự động tách",

        // Auth
        login: "Đăng nhập",
        signUp: "Đăng ký",
        emailAddress: "Địa chỉ Email",
        emailPlaceholder: "ten@vidu.com",
        password: "Mật khẩu",
        passwordPlaceholder: "Nhập mật khẩu của bạn",
        createPassword: "Tạo mật khẩu",
        forgotPassword: "Quên mật khẩu?",
        signIn: "Đăng nhập",
        or: "HOẶC",
        continueWithGoogle: "Tiếp tục với Google",
        connecting: "Đang kết nối...",
        protectedBy: "Được bảo vệ bởi reCAPTCHA và tuân theo Chính sách quyền riêng tư và Điều khoản dịch vụ.",
        rightsReserved: "Đã đăng ký bản quyền.",
        resetPassword: "Đặt lại mật khẩu",
        resetDesc: "Nhập địa chỉ email liên kết với tài khoản của bạn và chúng tôi sẽ gửi liên kết đặt lại mật khẩu.",
        sendResetLink: "Gửi liên kết",
        sending: "Đang gửi...",
        backToLogin: "Quay lại đăng nhập",
        checkEmail: "Kiểm tra email",
        checkEmailDesc: "Chúng tôi đã gửi hướng dẫn khôi phục mật khẩu đến email",
        didntReceive: "Không nhận được email?",
        clickToResend: "Bấm để gửi lại",
        createAccount: "Tạo tài khoản",
        step1: "Bước 1 / 3",
        step1Desc: "Bắt đầu tạo hình ảnh chuyên nghiệp ngay hôm nay.",
        fullName: "Họ và tên",
        namePlaceholder: "vd. Nguyễn Văn A",
        workEmail: "Email công việc",
        workEmailPlaceholder: "ten@congty.com",
        fair: "Bình thường",
        weak: "Yếu",
        good: "Tốt",
        strong: "Mạnh",
        passwordHint: "Sử dụng 8+ ký tự bao gồm chữ cái, số & ký tự đặc biệt.",
        nextStep: "Bước tiếp theo",
        alreadyHaveAccount: "Đã có tài khoản?",
        customizeStudio: "Tùy chỉnh Studio",
        almostDone: "SẮP HOÀN TẤT",
        step2Desc: "Giúp chúng tôi tối ưu hóa mô hình tạo ảnh cho sản phẩm của bạn.",
        primaryIndustry: "Ngành hàng chính",
        estGenerations: "Số lượng ảnh tạo hàng tháng (ước tính)",
        completeRegistration: "Hoàn tất đăng ký",
        secureConnection: "Kết nối an toàn & mã hóa",
        goBackStep1: "Quay lại bước 1",
        needHelp: "Cần trợ giúp? Liên hệ Hỗ trợ"
    }
};

export const INDUSTRIES: Industry[] = [
  { id: 'food-beverage', name: 'Food & Beverage' },
  { id: 'cosmetics', name: 'Cosmetics & Beauty' },
  { id: 'tech', name: 'Technology & Gadgets' },
  { id: 'fashion', name: 'Fashion & Apparel' },
  { id: 'jewelry', name: 'Jewelry & Accessories' },
  { id: 'homeware', name: 'Homeware & Decor' },
];

export const QUALITIES: Quality[] = [
  { id: 'standard', name: 'Standard', description: 'Good quality for web use.' },
  { id: 'hd', name: 'HD', description: 'High-definition, suitable for digital marketing.' },
  { id: 'ultra-hd', name: 'Ultra HD (4K)', description: 'Ultra-high resolution for premium digital and print.' },
];

export const GENERATION_FORMATS: GenerationFormat[] = [
  { id: 'poster', name: 'Poster (9:16)', className: 'aspect-[9/16]', value: '9:16' },
  { id: 'banner', name: 'Banner (16:9)', className: 'aspect-[16/9]', value: '16:9' },
  { id: 'square', name: 'Square (1:1)', className: 'aspect-square', value: '1:1' },
];

export const BACKGROUND_STYLES: BackgroundStyle[] = [
    { id: 'minimalist-gradient', name: 'Minimalist Gradient', prompt: 'A clean, minimalist studio background with a soft, two-tone gradient.', previewClass: 'bg-gradient-to-br from-gray-100 to-gray-300' },
    { id: 'soft-pink-studio', name: 'Soft Pink Studio', prompt: 'An elegant, soft pink studio background with a single soft light source.', previewClass: 'bg-gradient-to-br from-pink-100 to-rose-200' },
    { id: 'wooden-surface', name: 'Wooden Surface', prompt: 'A rustic, warm-toned wooden surface with a shallow depth of field, blurred background.', previewClass: 'bg-[url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADISURBVHhe7dChAYAwEATBif//2fAABmG5t11b1zRN0/T9Oz8fBwIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQhAAAIQgAAEIAABCEAAAhCAAAQhAAAIQgAAEIAABCEAAAhCAAAQhAAAIQgAAEIAABCECg8eT7wXJ3lAIAAAAASUVORK5CYII=)]' },
    { id: 'concrete-loft', name: 'Concrete Loft', prompt: 'An industrial chic setting with a polished concrete floor and a textured gray wall.', previewClass: 'bg-slate-300' },
    { id: 'nature-foliage', name: 'Nature Foliage', prompt: 'Lush, green tropical leaves and foliage creating a vibrant, natural backdrop.', previewClass: 'bg-gradient-to-br from-green-200 to-teal-300' },
    { id: 'dramatic-silk', name: 'Dramatic Silk', prompt: 'A background of flowing, draped black silk fabric, creating elegant folds and shadows.', previewClass: 'bg-gray-800' },
    // New Styles
    { id: 'marble-luxury', name: 'Marble Luxury', prompt: 'A luxurious white marble podium with subtle gold veins, bright high-key lighting, premium feel.', previewClass: 'bg-gradient-to-tr from-gray-100 via-white to-gray-200' },
    { id: 'sunny-kitchen', name: 'Sunny Kitchen', prompt: 'A bright, airy kitchen counter with morning sunlight streaming through a window, soft shadows.', previewClass: 'bg-gradient-to-r from-orange-50 to-yellow-50' },
    { id: 'neon-cyberpunk', name: 'Neon Cyberpunk', prompt: 'A futuristic dark background with glowing blue and purple neon lights, reflective surfaces.', previewClass: 'bg-gradient-to-br from-indigo-900 to-purple-900' },
    { id: 'blue-podium', name: 'Blue Podium', prompt: 'A modern, geometric 3D podium in shades of royal blue, clean lines, professional studio lighting.', previewClass: 'bg-gradient-to-b from-blue-500 to-blue-700' },
    { id: 'zen-garden', name: 'Zen Garden', prompt: 'A peaceful zen garden setting with smooth river stones, white sand, and soft natural light.', previewClass: 'bg-[#e3ded1]' },
    { id: 'water-ripple', name: 'Water Ripple', prompt: 'A fresh, aquatic scene with clear blue water ripples and caustic light effects.', previewClass: 'bg-cyan-200' },
];

export const FONTS: Font[] = [
    { id: 'poppins', name: 'Poppins', className: 'font-poppins', cssValue: '600 48px Poppins, sans-serif' },
    { id: 'playfair-display', name: 'Playfair Display', className: 'font-playfair-display', cssValue: 'bold 52px "Playfair Display", serif' },
    { id: 'lobster', name: 'Lobster', className: 'font-lobster', cssValue: 'normal 54px Lobster, cursive' },
    { id: 'roboto', name: 'Roboto', className: 'font-roboto', cssValue: 'bold 48px Roboto, sans-serif' },
    { id: 'montserrat', name: 'Montserrat', className: 'font-montserrat', cssValue: 'bold 48px Montserrat, sans-serif' },
];

export const FONT_SIZES_PRESET: number[] = [12, 16, 24, 32, 48, 64, 96, 128, 160];

export const TEXT_COLORS: ColorOption[] = [
    { id: 'white', name: 'White', value: '#FFFFFF', isGradient: false },
    { id: 'black', name: 'Black', value: '#000000', isGradient: false },
    { id: 'gold-rush', name: 'Gold Rush', value: 'linear-gradient(to right, #DAA520, #B8860B)', isGradient: true },
    { id: 'ocean-breeze', name: 'Ocean Breeze', value: 'linear-gradient(to right, #2E8B57, #48D1CC)', isGradient: true },
    { id: 'sunset-fade', name: 'Sunset Fade', value: 'linear-gradient(to right, #FF7F50, #FF4500)', isGradient: true },
    { id: 'royal-purple', name: 'Royal Purple', value: 'linear-gradient(to right, #8A2BE2, #4B0082)', isGradient: true },
];

export const FILTERS: FilterOption[] = [
    { id: 'none', name: 'Normal', value: 'none' },
    { id: 'vivid', name: 'Vivid', value: 'contrast(1.1) saturate(1.2)' },
    { id: 'soft', name: 'Soft', value: 'contrast(0.9) brightness(1.05) saturate(0.9)' },
    { id: 'warm', name: 'Warm', value: 'sepia(0.2) contrast(1.05)' },
    { id: 'cool', name: 'Cool', value: 'hue-rotate(10deg) contrast(0.95)' },
    { id: 'bw', name: 'B&W', value: 'grayscale(1)' },
    { id: 'vintage', name: 'Vintage', value: 'sepia(0.4) contrast(1.2) brightness(0.9)' },
];

export const BRAND_MODELS: BrandModel[] = [
    { id: 'modern', name: 'Modern', prompt: 'a modern, clean, and minimalist style' },
    { id: 'luxury', name: 'Luxury', prompt: 'a luxurious, elegant, and sophisticated style' },
    { id: 'playful', name: 'Playful', prompt: 'a playful, vibrant, and energetic style' },
    { id: 'natural', name: 'Natural', prompt: 'a natural, organic, and earthy style' },
    { id: 'vintage', name: 'Vintage', prompt: 'a vintage, retro, and nostalgic style' },
];
